package perpustakaan.language.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Anggota_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Buku_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Item_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Peminjaman_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Pengembalian_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Petugas_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Program_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Value_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3024L), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3044L), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa2e5fL), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3076L), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa305dL), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa2ce1L), MetaIdFactory.conceptId(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3444L)).seal();
}
