package perpustakaan.language.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Anggota = 0;
  public static final int Buku = 1;
  public static final int Item = 2;
  public static final int Peminjaman = 3;
  public static final int Pengembalian = 4;
  public static final int Petugas = 5;
  public static final int Program = 6;
  public static final int Value = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L);
    builder.put(0x6410ed4088fa3024L, Anggota);
    builder.put(0x6410ed4088fa3044L, Buku);
    builder.put(0x6410ed4088fa33a4L, Item);
    builder.put(0x6410ed4088fa2e5fL, Peminjaman);
    builder.put(0x6410ed4088fa3076L, Pengembalian);
    builder.put(0x6410ed4088fa305dL, Petugas);
    builder.put(0x6410ed4088fa2ce1L, Program);
    builder.put(0x6410ed4088fa3444L, Value);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
