package perpustakaan.language.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnggota = createDescriptorForAnggota();
  /*package*/ final ConceptDescriptor myConceptBuku = createDescriptorForBuku();
  /*package*/ final ConceptDescriptor myConceptItem = createDescriptorForItem();
  /*package*/ final ConceptDescriptor myConceptPeminjaman = createDescriptorForPeminjaman();
  /*package*/ final ConceptDescriptor myConceptPengembalian = createDescriptorForPengembalian();
  /*package*/ final ConceptDescriptor myConceptPetugas = createDescriptorForPetugas();
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnggota, myConceptBuku, myConceptItem, myConceptPeminjaman, myConceptPengembalian, myConceptPetugas, myConceptProgram, myConceptValue);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Anggota:
        return myConceptAnggota;
      case LanguageConceptSwitch.Buku:
        return myConceptBuku;
      case LanguageConceptSwitch.Item:
        return myConceptItem;
      case LanguageConceptSwitch.Peminjaman:
        return myConceptPeminjaman;
      case LanguageConceptSwitch.Pengembalian:
        return myConceptPengembalian;
      case LanguageConceptSwitch.Petugas:
        return myConceptPetugas;
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.Value:
        return myConceptValue;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnggota() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Anggota", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3024L);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851951652");
    b.version(3);
    b.aggregate("items", 0x6410ed4088fa31f9L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L).optional(false).ordered(true).multiple(false).origin("7210523864851952121").done();
    b.alias("anggota");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBuku() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Buku", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3044L);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851951684");
    b.version(3);
    b.aggregate("items", 0x6410ed4088fa3273L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L).optional(false).ordered(true).multiple(true).origin("7210523864851952243").done();
    b.alias("buku");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Item", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851952548");
    b.version(3);
    b.property("key", 0x6410ed4088fa33e8L).type(PrimitiveTypeId.STRING).origin("7210523864851952616").done();
    b.aggregate("value", 0x6410ed4088fa3401L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3444L).optional(false).ordered(true).multiple(false).origin("7210523864851952641").done();
    b.alias("item");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPeminjaman() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Peminjaman", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa2e5fL);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851951199");
    b.version(3);
    b.property("id", 0x6410ed4088fa2efeL).type(PrimitiveTypeId.STRING).origin("7210523864851951358").done();
    b.aggregate("anggota", 0x6410ed4088fa2f18L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3024L).optional(false).ordered(true).multiple(false).origin("7210523864851951384").done();
    b.aggregate("buku", 0x6410ed4088fa2f5bL).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3044L).optional(false).ordered(true).multiple(true).origin("7210523864851951451").done();
    b.aggregate("petugas", 0x6410ed4088fa2fb6L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa305dL).optional(false).ordered(true).multiple(false).origin("7210523864851951542").done();
    b.aggregate("pengembalian", 0x6410ed4088fa2fe7L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3076L).optional(false).ordered(true).multiple(true).origin("7210523864851951591").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPengembalian() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Pengembalian", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3076L);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851951734");
    b.version(3);
    b.aggregate("items", 0x6410ed4088fa3360L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L).optional(false).ordered(true).multiple(true).origin("7210523864851952480").done();
    b.alias("pengembalian");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPetugas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Petugas", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa305dL);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851951709");
    b.version(3);
    b.aggregate("items", 0x6410ed4088fa32edL).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa33a4L).optional(false).ordered(true).multiple(false).origin("7210523864851952365").done();
    b.alias("petugas");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Program", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa2ce1L);
    b.class_(false, false, true);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851950817");
    b.version(3);
    b.aggregate("peminjaman", 0x6410ed4088fa2da3L).target(0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa2e5fL).optional(false).ordered(true).multiple(true).origin("7210523864851951011").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("perpustakaan.language", "Value", 0x1f2e2539878a4e98L, 0xac085c5c9c490ce7L, 0x6410ed4088fa3444L);
    b.class_(false, false, false);
    b.origin("r:5aef5bf2-bde3-405a-8e58-f8d80e83f994(perpustakaan.language.structure)/7210523864851952708");
    b.version(3);
    b.property("text", 0x5420f97afca6b858L).type(PrimitiveTypeId.STRING).origin("6062119405060798552").done();
    return b.create();
  }
}
